.include "m2560def.inc"
.def ledOutput = r16

; Initialize SP, Stack Pointer
ldi r20, HIGH(RAMEND)					; R20 = high part of RAMEND address
out SPH,R20								; SPH = high part of RAMEND address
ldi R20, low(RAMEND)					; R20 = low part of RAMEND address
out SPL,R20								; SPL = low part of RAMEND address

ldi r17, 0xFF
out DDRB, r17
	ldi ledOutput, 0x01

loop:
	out PORTB, ledOutput
	rcall delay
	sbic PORTB, 0x07
	ldi ledOutput, 0x01
	sbis PORTB, 0x07
	lsl ledOutput
	rjmp loop

; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 4 000 000 cycles
; 500ms at 8.0 MHz
delay:
    ldi  r18, 21
    ldi  r19, 75
    ldi  r21, 191
L1: dec  r21
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    nop
	ret