.include "m2560def.inc"
.def currentValue = r16
.def multiplier = r17

; Initialize SP, Stack Pointer
ldi r20, HIGH(RAMEND)					; R20 = high part of RAMEND address
out SPH,R20								; SPH = high part of RAMEND address
ldi R20, low(RAMEND)					; R20 = low part of RAMEND address
out SPL,R20								; SPL = low part of RAMEND address

ldi currentValue, 0x00
ldi multiplier, 0x02

ldi r18, 0xFF
out DDRB, r18

count_up:
	sbic PORTB, PINB7
	rjmp count_down
	mul currentValue, multiplier
	mov currentValue, r0
	inc currentValue
	out PORTB, currentValue
	rcall delay_500ms
	rjmp count_up

count_down:
	sbis PORTB, PINB0
	rjmp count_up
	lsr currentValue
	out PORTB, currentValue
	rcall delay_500ms
	rjmp count_down

; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 4 000 000 cycles
; 500ms at 8.0 MHz
delay_500ms:
    ldi  r18, 21
    ldi  r19, 75
    ldi  r21, 191
L1: dec  r21
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    nop
	ret
